default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_manifest: false
  extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
    - .css
    - .scss

development:
  <<: *default
  compile: true
  extract_css: true
  check_yarn_integrity: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035

test:
  <<: *default
  compile: true
  extract_css: false

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true