class PopulateDeweyCodes < ActiveRecord::Migration[7.1]
  def change
    dewey_codes = [
      # Level 1 Categories
      { level: 1, code: '0', description: 'Information' },
      { level: 1, code: '1', description: 'Philosophy & Psychology' },
      { level: 1, code: '2', description: 'Religion' },
      { level: 1, code: '3', description: 'Social Sciences' },
      { level: 1, code: '4', description: 'Language' },
      { level: 1, code: '5', description: 'Natural sciences and mathematics' },
      { level: 1, code: '6', description: 'Technology' },
      { level: 1, code: '7', description: 'The Arts' },
      { level: 1, code: '8', description: 'Literature' },
      { level: 1, code: '9', description: 'History & Geography' },

      # Level 2
      { level: 2, code: '00', description: 'Computer science, knowledge, and systems' },
      { level: 2, code: '01', description: 'Bibliographies' },
      { level: 2, code: '02', description: 'Library and information sciences' },
      { level: 2, code: '03', description: 'Encyclopedias and books of facts' },
      { level: 2, code: '04', description: 'Unassigned (formerly Biographies)' },

      # Level 3
      { level: 3, code: '000', description: 'Computer science, information, and general works' },
      { level: 3, code: '001', description: 'Knowledge' },
      { level: 3, code: '002', description: 'The book (writing, libraries, and book-related topics)' },
      { level: 3, code: '003', description: 'Systems' },
      { level: 3, code: '004', description: 'Data processing and computer science' },
      { level: 3, code: '005', description: 'Computer programming, programs, and data' },
      { level: 3, code: '006', description: 'Special computer methods (e.g., AI, multimedia, VR)' },
      { level: 3, code: '010', description: 'Bibliography' },
      { level: 3, code: '011', description: 'Bibliographies' },
      { level: 3, code: '012', description: 'Bibliographies of individuals' },
      { level: 3, code: '014', description: 'Bibliographies of anonymous and pseudonymous works' },
      { level: 3, code: '015', description: 'Bibliographies of works from specific places' },
      { level: 3, code: '016', description: 'Bibliographies of works on specific subjects' },
      { level: 3, code: '017', description: 'General subject catalogs' },

      # 020s
      { level: 3, code: '020', description: 'Library and information sciences' },
      { level: 3, code: '021', description: 'Library relationships (with archives, information centers, etc.)' },
      { level: 3, code: '022', description: 'Administration of physical plant' },
      { level: 3, code: '023', description: 'Personnel management' },
      { level: 3, code: '025', description: 'Library operations' },
      { level: 3, code: '026', description: 'Libraries for specific subjects' },
      { level: 3, code: '027', description: 'General libraries' },
      { level: 3, code: '028', description: 'Reading and use of other information media' },

      # 030s
      { level: 3, code: '030', description: 'General encyclopedic works' },
      { level: 3, code: '031', description: 'Encyclopedias in American English' },
      { level: 3, code: '032', description: 'Encyclopedias in English' },
      { level: 3, code: '033', description: 'Encyclopedias in other Germanic languages' },
      { level: 3, code: '034', description: 'Encyclopedias in French, Occitan, and Catalan' },
      { level: 3, code: '035', description: 'Encyclopedias in Italian, Romanian, and related languages' },
      { level: 3, code: '036', description: 'Encyclopedias in Spanish and Portuguese' },
      { level: 3, code: '037', description: 'Encyclopedias in Slavic languages' },
      { level: 3, code: '038', description: 'Encyclopedias in Scandinavian languages' },
      { level: 3, code: '039', description: 'Encyclopedias in other languages' },

      # 050s
      { level: 2, code: '05', description: 'Magazines, journals, and serials' },
      { level: 3, code: '050', description: 'General serial publications' },
      { level: 3, code: '051', description: 'Serials in American English' },
      { level: 3, code: '052', description: 'Serials in English' },
      { level: 3, code: '053', description: 'Serials in other Germanic languages' },
      { level: 3, code: '054', description: 'Serials in French, Occitan, and Catalan' },
      { level: 3, code: '055', description: 'Serials in Italian, Romanian, and related languages' },
      { level: 3, code: '056', description: 'Serials in Spanish and Portuguese' },
      { level: 3, code: '057', description: 'Serials in Slavic languages' },
      { level: 3, code: '058', description: 'Serials in Scandinavian languages' },
      { level: 3, code: '059', description: 'Serials in other languages' },

      # 060s
      { level: 2, code: '06', description: 'Associations, organizations, and museums' },
      { level: 3, code: '060', description: 'General organizations and museum science' },
      { level: 3, code: '061', description: 'Organizations in North America' },
      { level: 3, code: '062', description: 'Organizations in British Isles; in England' },
      { level: 3, code: '063', description: 'Organizations in central Europe; in Germany' },
      { level: 3, code: '064', description: 'Organizations in France and Monaco' },
      { level: 3, code: '065', description: 'Organizations in Italy and adjacent islands' },
      { level: 3, code: '066', description: 'Organizations in Iberian Peninsula and adjacent islands' },
      { level: 3, code: '067', description: 'Organizations in eastern Europe; in Russia' },
      { level: 3, code: '068', description: 'Organizations in other geographic areas' },
      { level: 3, code: '069', description: 'Museum science' },

      # 070s
      { level: 2, code: '07', description: 'News media, journalism, and publishing' },
      { level: 3, code: '070', description: 'News media, journalism, and publishing' },
      { level: 3, code: '071', description: 'Newspapers in North America' },
      { level: 3, code: '072', description: 'Newspapers in British Isles; in England' },
      { level: 3, code: '073', description: 'Newspapers in central Europe; in Germany' },
      { level: 3, code: '074', description: 'Newspapers in France and Monaco' },
      { level: 3, code: '075', description: 'Newspapers in Italy and adjacent islands' },
      { level: 3, code: '076', description: 'Newspapers in Iberian peninsula and adjacent islands' },
      { level: 3, code: '077', description: 'Newspapers in eastern Europe; in Russia' },
      { level: 3, code: '078', description: 'Newspapers in Scandinavia' },
      { level: 3, code: '079', description: 'Newspapers in other geographic areas' },

      # 080s
      { level: 2, code: '08', description: 'Quotations' },
      { level: 3, code: '080', description: 'General collections' },
      { level: 3, code: '081', description: 'Collections in American English' },
      { level: 3, code: '082', description: 'Collections in English' },
      { level: 3, code: '083', description: 'Collections in other Germanic languages' },
      { level: 3, code: '084', description: 'Collections in French, Occitan, Catalan' },
      { level: 3, code: '085', description: 'Collections in Italian, Romanian, and related languages' },
      { level: 3, code: '086', description: 'Collections in Spanish and Portuguese' },
      { level: 3, code: '087', description: 'Collections in Slavic languages' },
      { level: 3, code: '088', description: 'Collections in Scandinavian languages' },
      { level: 3, code: '089', description: 'Collections in other languages' },

      # 090s
      { level: 2, code: '09', description: 'Manuscripts and rare books' },
      { level: 3, code: '090', description: 'Manuscripts and rare books' },
      { level: 3, code: '091', description: 'Manuscripts' },
      { level: 3, code: '092', description: 'Block books' },
      { level: 3, code: '093', description: 'Incunabula' },
      { level: 3, code: '094', description: 'Printed books' },
      { level: 3, code: '095', description: 'Books notable for bindings' },
      { level: 3, code: '096', description: 'Books notable for illustrations' },
      { level: 3, code: '097', description: 'Books notable for ownership or origin' },
      { level: 3, code: '098', description: 'Prohibited works, forgeries, and hoaxes' },
      { level: 3, code: '099', description: 'Books notable for format' },

      # 100s
      { level: 2, code: '10', description: 'Philosophy' },
      { level: 3, code: '100', description: 'Philosophy and psychology' },
      { level: 3, code: '101', description: 'Theory of philosophy' },
      { level: 3, code: '102', description: 'Miscellany' },
      { level: 3, code: '103', description: 'Dictionaries and encyclopedias' },
      { level: 3, code: '105', description: 'Serial publications' },
      { level: 3, code: '106', description: 'Organizations and management' },
      { level: 3, code: '107', description: 'Education, research, related topics of philosophy' },
      { level: 3, code: '108', description: 'Groups of people' },
      { level: 3, code: '109', description: 'History and collected biography' },

      # 110s
      { level: 2, code: '11', description: 'Metaphysics' },
      { level: 3, code: '110', description: 'Metaphysics' },
      { level: 3, code: '111', description: 'Ontology' },
      { level: 3, code: '113', description: 'Cosmology (Philosophy of nature)' },
      { level: 3, code: '114', description: 'Space' },
      { level: 3, code: '115', description: 'Time' },
      { level: 3, code: '116', description: 'Change' },
      { level: 3, code: '117', description: 'Structure' },
      { level: 3, code: '118', description: 'Force and energy' },
      { level: 3, code: '119', description: 'Number and quantity' },

      # 120s
      { level: 2, code: '12', description: 'Epistemology' },
      { level: 3, code: '120', description: 'Epistemology, causation, and humankind' },
      { level: 3, code: '121', description: 'Epistemology (Theory of knowledge)' },
      { level: 3, code: '122', description: 'Causation' },
      { level: 3, code: '123', description: 'Determinism and indeterminism' },
      { level: 3, code: '124', description: 'Teleology' },
      { level: 3, code: '126', description: 'The self' },
      { level: 3, code: '127', description: 'The unconscious and the subconscious' },
      { level: 3, code: '128', description: 'Humankind' },
      { level: 3, code: '129', description: 'Origin and destiny of individual souls' },

      # 130s
      { level: 2, code: '13', description: 'Parapsychology and occultism' },
      { level: 3, code: '130', description: 'Parapsychology and occultism' },
      { level: 3, code: '131', description: 'Parapsychological and occult methods for achieving well-being, happiness, success' },
      { level: 3, code: '133', description: 'Specific topics in parapsychology and occultism' },
      { level: 3, code: '135', description: 'Dreams and mysteries' },
      { level: 3, code: '137', description: 'Divinatory graphology' },
      { level: 3, code: '138', description: 'Physiognomy' },
      { level: 3, code: '139', description: 'Phrenology' },

      # 140s
      { level: 2, code: '14', description: 'Philosophical schools of thought' },
      { level: 3, code: '140', description: 'Specific philosophical schools and viewpoints' },
      { level: 3, code: '141', description: 'Idealism and related systems and doctrines' },
      { level: 3, code: '142', description: 'Critical philosophy' },
      { level: 3, code: '143', description: 'Bergsonism and intuitionism' },
      { level: 3, code: '144', description: 'Humanism and related systems and doctrines' },
      { level: 3, code: '145', description: 'Sensationalism' },
      { level: 3, code: '146', description: 'Naturalism and related systems and doctrines' },
      { level: 3, code: '147', description: 'Pantheism and related systems and doctrines' },
      { level: 3, code: '148', description: 'Dogmatism, eclecticism, liberalism, syncretism, and traditionalism' },
      { level: 3, code: '149', description: 'Other philosophical systems and doctrines' },

      # 150s
      { level: 2, code: '15', description: 'Psychology' },
      { level: 3, code: '150', description: 'Psychology' },
      { level: 3, code: '152', description: 'Sensory perception, movement, emotions, and physiological drives' },
      { level: 3, code: '153', description: 'Conscious mental processes and intelligence' },
      { level: 3, code: '154', description: 'Subconscious and altered states and processes' },
      { level: 3, code: '155', description: 'Differential and developmental psychology' },
      { level: 3, code: '156', description: 'Comparative psychology' },
      { level: 3, code: '158', description: 'Applied psychology' },

      # 160s
      { level: 2, code: '16', description: 'Philosophical logic' },
      { level: 3, code: '160', description: 'Philosophical logic' },
      { level: 3, code: '161', description: 'Induction' },
      { level: 3, code: '162', description: 'Deduction' },
      { level: 3, code: '165', description: 'Fallacies and sources of error' },
      { level: 3, code: '166', description: 'Syllogisms' },
      { level: 3, code: '167', description: 'Hypotheses' },
      { level: 3, code: '168', description: 'Argument and persuasion' },
      { level: 3, code: '169', description: 'Analogy' },

      # 170s
      { level: 2, code: '17', description: 'Ethics' },
      { level: 3, code: '170', description: 'Ethics (Moral philosophy)' },
      { level: 3, code: '171', description: 'Ethical systems' },
      { level: 3, code: '172', description: 'Political ethics' },
      { level: 3, code: '173', description: 'Ethics of family relationships' },
      { level: 3, code: '174', description: 'Occupational ethics' },
      { level: 3, code: '175', description: 'Ethics of recreation, leisure, public performances, communication' },
      { level: 3, code: '176', description: 'Ethics of sex and reproduction' },
      { level: 3, code: '177', description: 'Ethics of social relations' },
      { level: 3, code: '178', description: 'Ethics of consumption' },
      { level: 3, code: '179', description: 'Other ethical norms' },

      # 180s
      { level: 2, code: '18', description: 'Ancient, medieval, and Eastern philosophy' },
      { level: 3, code: '180', description: 'Ancient, medieval, Eastern philosophy' },
      { level: 3, code: '181', description: 'Eastern philosophy' },
      { level: 3, code: '182', description: 'Pre-Socratic Greek philosophies' },
      { level: 3, code: '183', description: 'Sophistic, Socratic, related Greek philosophies' },
      { level: 3, code: '184', description: 'Platonic philosophy' },
      { level: 3, code: '185', description: 'Aristotelian philosophy' },
      { level: 3, code: '186', description: 'Skeptic and Neoplatonic philosophies' },
      { level: 3, code: '187', description: 'Epicurean philosophy' },
      { level: 3, code: '188', description: 'Stoic philosophy' },
      { level: 3, code: '189', description: 'Medieval Western philosophy' },

      # 190s
      { level: 2, code: '19', description: 'Modern Western philosophy (19th-century, 20th-century)' },
      { level: 3, code: '190', description: 'Modern Western and other non-Eastern philosophy' },
      { level: 3, code: '191', description: 'Philosophy of the United States and Canada' },
      { level: 3, code: '192', description: 'Philosophy of the British Isles' },
      { level: 3, code: '193', description: 'Philosophy of Germany and Austria' },
      { level: 3, code: '194', description: 'Philosophy of France' },
      { level: 3, code: '195', description: 'Philosophy of Italy' },
      { level: 3, code: '196', description: 'Philosophy of Spain and Portugal' },
      { level: 3, code: '197', description: 'Philosophy of Russia' },
      { level: 3, code: '198', description: 'Philosophy of Scandinavia and Finland' },
      { level: 3, code: '199', description: 'Philosophy in other geographic areas' },

      # 200s
      { level: 2, code: '20', description: 'Religion' },
      { level: 3, code: '200', description: 'Religion' },
      { level: 3, code: '201', description: 'Religious mythology, general classes of religion, interreligious relations and attitudes, social theology' },
      { level: 3, code: '202', description: 'Doctrines' },
      { level: 3, code: '203', description: 'Public worship and other practices' },
      { level: 3, code: '204', description: 'Religious experience, life, practice' },
      { level: 3, code: '205', description: 'Religious ethics' },
      { level: 3, code: '206', description: 'Leaders and organization' },
      { level: 3, code: '207', description: 'Missions and religious education' },
      { level: 3, code: '208', description: 'Sources' },
      { level: 3, code: '209', description: 'Sects and reform movements' },
      { level: 2, code: '21', description: 'Philosophy and theory of religion' },
      { level: 3, code: '210', description: 'Philosophy and theory of religion' },
      { level: 3, code: '211', description: 'Concepts of God' },
      { level: 3, code: '212', description: 'Existence, ways of knowing God, attributes of God' },
      { level: 3, code: '213', description: 'Creation' },
      { level: 3, code: '214', description: 'Theodicy' },
      { level: 3, code: '215', description: 'Science and religion' },
      { level: 2, code: '22', description: 'The Bible' },
      { level: 3, code: '220', description: 'Bible' },
      { level: 3, code: '221', description: 'Old Testament (Tanakh)' },
      { level: 3, code: '222', description: 'Historical books of Old Testament' },
      { level: 3, code: '223', description: 'Poetic books of Old Testament' },
      { level: 3, code: '224', description: 'Prophetic books of Old Testament' },
      { level: 3, code: '225', description: 'New Testament' },
      { level: 3, code: '226', description: 'Gospels and Acts' },
      { level: 3, code: '227', description: 'Epistles' },
      { level: 3, code: '228', description: 'Revelation (Apocalypse)' },
      { level: 3, code: '229', description: 'Apocrypha, pseudepigrapha, and inter-testamental works' },
      { level: 2, code: '23', description: 'Christianity' },
      { level: 3, code: '230', description: 'Christianity' },
      { level: 3, code: '231', description: 'God' },
      { level: 3, code: '232', description: 'Jesus Christ and his family' },
      { level: 3, code: '233', description: 'Humankind' },
      { level: 3, code: '234', description: 'Salvation and grace' },
      { level: 3, code: '235', description: 'Spiritual beings' },
      { level: 3, code: '236', description: 'Eschatology' },
      { level: 3, code: '238', description: 'Creeds, confessions of faith, covenants, and catechisms' },
      { level: 3, code: '239', description: 'Apologetics and polemics' },
      { level: 2, code: '24', description: 'Christian practice and observance' },
      { level: 3, code: '240', description: 'Christian moral and devotional theology' },
      { level: 3, code: '241', description: 'Christian ethics' },
      { level: 3, code: '242', description: 'Devotional literature' },
      { level: 3, code: '243', description: 'Evangelistic writings for individuals and families' },
      { level: 3, code: '246', description: 'Use of art in Christianity' },
      { level: 3, code: '247', description: 'Church furnishings and related articles' },
      { level: 3, code: '248', description: 'Christian experience, practice, life' },
      { level: 3, code: '249', description: 'Christian observances in family life' },
      { level: 2, code: '25', description: 'Christian orders and local church' },
      { level: 3, code: '250', description: 'Local Christian church and Christian religious orders' },
      { level: 3, code: '251', description: 'Preaching (Homiletics)' },
      { level: 3, code: '252', description: 'Texts of sermons' },
      { level: 3, code: '253', description: 'Pastoral office and work (Pastoral theology)' },
      { level: 3, code: '254', description: 'Parish administration' },
      { level: 3, code: '255', description: 'Religious congregations and orders' },
      { level: 2, code: '26', description: 'Social and ecclesiastical theology' },
      { level: 3, code: '260', description: 'Christian social and ecclesiastical theology' },
      { level: 3, code: '261', description: 'Social theology and interreligious relations and attitudes' },
      { level: 3, code: '262', description: 'Ecclesiology' },
      { level: 3, code: '263', description: 'Days, times, places of religious observance' },
      { level: 3, code: '264', description: 'Public worship' },
      { level: 3, code: '265', description: 'Sacraments, other rites and acts' },
      { level: 3, code: '266', description: 'Missions' },
      { level: 3, code: '267', description: 'Associations for religious work' },
      { level: 3, code: '268', description: 'Religious education' },
      { level: 3, code: '269', description: 'Spiritual renewal' },
      { level: 2, code: '27', description: 'History of Christianity' },
      { level: 3, code: '270', description: 'History, geographic treatment, biography of Christianity' },
      { level: 3, code: '271', description: 'Religious congregations and orders in church history' },
      { level: 3, code: '272', description: 'Persecutions in church history' },
      { level: 3, code: '273', description: 'Doctrinal controversies and heresies in general church history' },
      { level: 3, code: '274', description: 'Christianity in Europe' },
      { level: 3, code: '275', description: 'Christianity in Asia' },
      { level: 3, code: '276', description: 'Christianity in Africa' },
      { level: 3, code: '277', description: 'Christianity in North America' },
      { level: 3, code: '278', description: 'Christianity in South America' },
      { level: 3, code: '279', description: 'History of Christianity in other areas' },
      { level: 2, code: '28', description: 'Christian denominations' },
      { level: 3, code: '280', description: 'Denominations and sects of Christian church' },
      { level: 3, code: '281', description: 'Early church and Eastern churches' },
      { level: 3, code: '282', description: 'Roman Catholic Church' },
      { level: 3, code: '283', description: 'Anglican churches' },
      { level: 3, code: '284', description: 'Protestant denominations of Continental origin (Lutheran, Continental Reformed)' },
      { level: 3, code: '285', description: 'Presbyterian churches, Reformed churches centered in America, Congregational churches' },
      { level: 3, code: '286', description: 'Baptist, Restoration Movement, Adventist churches' },
      { level: 3, code: '287', description: 'Methodist churches; churches related to Methodism' },
      { level: 3, code: '289', description: 'Other denominations and sects' },
      { level: 2, code: '29', description: 'Other religions' },
      { level: 3, code: '290', description: 'Other religions' },
      { level: 3, code: '292', description: 'Classical religion (Greek and Roman religion)' },
      { level: 3, code: '293', description: 'Germanic religion' },
      { level: 3, code: '294', description: 'Religions of Indic origin' },
      { level: 3, code: '295', description: 'Zoroastrianism (Mazdaism, Parseeism)' },
      { level: 3, code: '296', description: 'Judaism' },
      { level: 3, code: '297', description: 'Islam, Bábism, and Baháʼí Faith' },
      { level: 3, code: '299', description: 'Religions not provided for elsewhere' },

    # 300s
      { level: 2, code: '30', description: 'Social sciences, sociology, and anthropology' },
      { level: 3, code: '300', description: 'Social sciences' },
      { level: 3, code: '301', description: 'Sociology and anthropology' },
      { level: 3, code: '302', description: 'Social interaction' },
      { level: 3, code: '303', description: 'Social processes' },
      { level: 3, code: '304', description: 'Factors affecting social behavior' },
      { level: 3, code: '305', description: 'Groups of people' },
      { level: 3, code: '306', description: 'Culture and institutions' },
      { level: 3, code: '307', description: 'Communities' },
      { level: 2, code: '31', description: 'Statistics' },
      { level: 3, code: '310', description: 'Statistics' },
      { level: 3, code: '311', description: 'Collections of general statistics' },
      { level: 3, code: '314', description: 'General statistics of Europe' },
      { level: 3, code: '315', description: 'General statistics of Asia' },
      { level: 3, code: '316', description: 'General statistics of Africa' },
      { level: 3, code: '317', description: 'General statistics of North America' },
      { level: 3, code: '318', description: 'General statistics of South America' },
      { level: 3, code: '319', description: 'General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica' },
      { level: 2, code: '32', description: 'Political science' },
      { level: 3, code: '320', description: 'Political science (Politics and government)' },
      { level: 3, code: '321', description: 'Systems of governments and states' },
      { level: 3, code: '322', description: 'Relation of state to organized groups and their members' },
      { level: 3, code: '323', description: 'Civil and political rights' },
      { level: 3, code: '324', description: 'The political process' },
      { level: 3, code: '325', description: 'International migration and colonization' },
      { level: 3, code: '326', description: 'Slavery and emancipation' },
      { level: 3, code: '327', description: 'International relations' },
      { level: 3, code: '328', description: 'The legislative process' },
      { level: 2, code: '33', description: 'Economics' },
      { level: 3, code: '330', description: 'Economics' },
      { level: 3, code: '331', description: 'Labor economics' },
      { level: 3, code: '332', description: 'Financial economics' },
      { level: 3, code: '333', description: 'Economics of land and energy' },
      { level: 3, code: '334', description: 'Cooperatives' },
      { level: 3, code: '335', description: 'Socialism and related systems' },
      { level: 3, code: '336', description: 'Public finance' },
      { level: 3, code: '337', description: 'International economics' },
      { level: 3, code: '338', description: 'Production' },
      { level: 3, code: '339', description: 'Macroeconomics and related topics' },
      { level: 2, code: '34', description: 'Law' },
      { level: 3, code: '340', description: 'Law' },
      { level: 3, code: '341', description: 'Law of nations' },
      { level: 3, code: '342', description: 'Constitutional and administrative law' },
      { level: 3, code: '343', description: 'Military, defense, public property, public finance, tax, commerce (trade), industrial law' },
      { level: 3, code: '344', description: 'Labor, social service, education, cultural law' },
      { level: 3, code: '345', description: 'Criminal law' },
      { level: 3, code: '346', description: 'Private law' },
      { level: 3, code: '347', description: 'Procedure and courts' },
      { level: 3, code: '348', description: 'Laws, regulations, cases' },
      { level: 3, code: '349', description: 'Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations' },
      { level: 2, code: '35', description: 'Public administration and military science' },
      { level: 3, code: '350', description: 'Public administration and military science' },
      { level: 3, code: '351', description: 'Public administration' },
      { level: 3, code: '352', description: 'General considerations of public administration' },
      { level: 3, code: '353', description: 'Specific fields of public administration' },
      { level: 3, code: '354', description: 'Public administration of economy and environment' },
      { level: 3, code: '355', description: 'Military science' },
      { level: 3, code: '356', description: 'Foot forces and warfare' },
      { level: 3, code: '357', description: 'Mounted forces and warfare' },
      { level: 3, code: '358', description: 'Air and other specialized forces and warfare; engineering and related services' },
      { level: 3, code: '359', description: 'Sea forces and warfare' },
      { level: 2, code: '36', description: 'Social problems and social services' },
      { level: 3, code: '360', description: 'Social problems and services; associations' },
      { level: 3, code: '361', description: 'Social problems and services' },
      { level: 3, code: '362', description: 'Social problems of and services to groups of people' },
      { level: 3, code: '363', description: 'Other social problems and services' },
      { level: 3, code: '364', description: 'Criminology' },
      { level: 3, code: '365', description: 'Penal and related institutions' },
      { level: 3, code: '366', description: 'Secret associations and societies' },
      { level: 3, code: '367', description: 'General clubs' },
      { level: 3, code: '368', description: 'Insurance' },
      { level: 3, code: '369', description: 'Associations' },
      { level: 2, code: '37', description: 'Education' },
      { level: 3, code: '370', description: 'Education' },
      { level: 3, code: '371', description: 'Schools and their activities, special education' },
      { level: 3, code: '372', description: 'Primary education (elementary education)' },
      { level: 3, code: '373', description: 'Secondary education' },
      { level: 3, code: '374', description: 'Adult education' },
      { level: 3, code: '375', description: 'Curriculum' },
      { level: 3, code: '378', description: 'Higher education (Tertiary education)' },
      { level: 3, code: '379', description: 'Public policy issues in education' },
      { level: 2, code: '38', description: 'Commerce, communications and transportation' },
      { level: 3, code: '380', description: 'Commerce, communications transportation' },
      { level: 3, code: '381', description: 'Commerce (Trade)' },
      { level: 3, code: '382', description: 'International commerce (Foreign trade)' },
      { level: 3, code: '383', description: 'Postal communication' },
      { level: 3, code: '384', description: 'Communications' },
      { level: 3, code: '385', description: 'Railroad transportation' },
      { level: 3, code: '386', description: 'Inland waterway and ferry transportation' },
      { level: 3, code: '387', description: 'Water, air, space transportation' },
      { level: 3, code: '388', description: 'Transportation' },
      { level: 3, code: '389', description: 'Metrology and standardization' },
      { level: 2, code: '39', description: 'Customs, etiquette and folklore' },
      { level: 3, code: '390', description: 'Customs, etiquette, folklore' },
      { level: 3, code: '391', description: 'Costume and personal appearance' },
      { level: 3, code: '392', description: 'Customs of life cycle and domestic life' },
      { level: 3, code: '393', description: 'Death customs' },
      { level: 3, code: '394', description: 'General customs' },
      { level: 3, code: '395', description: 'Etiquette (Manners)' },
      { level: 3, code: '398', description: 'Folklore' },
      { level: 3, code: '399', description: 'Customs of war and diplomacy' },

      # 400s
      { level: 2, code: '40', description: 'Language' },
      { level: 3, code: '400', description: 'Language' },
      { level: 3, code: '401', description: 'Philosophy and theory, international languages' },
      { level: 3, code: '402', description: 'Miscellany' },
      { level: 3, code: '403', description: 'Dictionaries, encyclopedias, concordances' },
      { level: 3, code: '404', description: 'Special topics of language' },
      { level: 3, code: '405', description: 'Serial publications' },
      { level: 3, code: '406', description: 'Organizations and management' },
      { level: 3, code: '407', description: 'Education, research, related topics' },
      { level: 3, code: '408', description: 'Groups of people' },
      { level: 3, code: '409', description: 'Geographic treatment and biography' },
      { level: 2, code: '41', description: 'Linguistics' },
      { level: 3, code: '410', description: 'Linguistics' },
      { level: 3, code: '411', description: 'Writing systems of standard forms of languages' },
      { level: 3, code: '412', description: 'Etymology of standard forms of languages' },
      { level: 3, code: '413', description: 'Dictionaries of standard forms of languages' },
      { level: 3, code: '414', description: 'Phonology and phonetics of standard forms of languages' },
      { level: 3, code: '415', description: 'Grammar of standard forms of languages' },
      { level: 3, code: '417', description: 'Dialectology and historical linguistics' },
      { level: 3, code: '418', description: 'Standard usage (Prescriptive linguistics)' },
      { level: 3, code: '419', description: 'Sign languages' },
      { level: 2, code: '42', description: 'English and Old English languages' },
      { level: 3, code: '420', description: 'English and Old English (Anglo-Saxon)' },
      { level: 3, code: '421', description: 'Writing system, phonology, phonetics of standard English' },
      { level: 3, code: '422', description: 'Etymology of standard English' },
      { level: 3, code: '423', description: 'Dictionaries of standard English' },
      { level: 3, code: '425', description: 'Grammar of standard English' },
      { level: 3, code: '427', description: 'Historical and geographical variations, modern nongeographic variations of English' },
      { level: 3, code: '428', description: 'Standard English usage (Prescriptive linguistics)' },
      { level: 3, code: '429', description: 'Old English (Anglo-Saxon)' },
      { level: 2, code: '43', description: 'German and related languages' },
      { level: 3, code: '430', description: 'German and related languages' },
      { level: 3, code: '431', description: 'Writing systems, phonology, phonetics of standard German' },
      { level: 3, code: '432', description: 'Etymology of standard German' },
      { level: 3, code: '433', description: 'Dictionaries of standard German' },
      { level: 3, code: '435', description: 'Grammar of standard German' },
      { level: 3, code: '437', description: 'Historical and geographic variations, modern nongeographic variations of German' },
      { level: 3, code: '438', description: 'Standard German usage (Prescriptive linguistics)' },
      { level: 2, code: '44', description: 'French and related languages' },
      { level: 3, code: '440', description: 'French and related Romance languages' },
      { level: 3, code: '441', description: 'Writing systems, phonology, phonetics of standard French' },
      { level: 3, code: '442', description: 'Etymology of standard French' },
      { level: 3, code: '443', description: 'Dictionaries of standard French' },
      { level: 3, code: '445', description: 'Grammar of standard French' },
      { level: 3, code: '447', description: 'Historical and geographic variations, modern nongeographic variations of French' },
      { level: 3, code: '448', description: 'Standard French usage (Prescriptive linguistics)' },
      { level: 3, code: '449', description: 'Occitan Catalan, Franco-Provençal' },
      { level: 2, code: '45', description: 'Italian, Romanian and related languages' },
      { level: 3, code: '450', description: 'Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican' },
      { level: 3, code: '451', description: 'Writing systems, phonology, phonetics of standard Italian' },
      { level: 3, code: '452', description: 'Etymology of standard Italian' },
      { level: 3, code: '453', description: 'Dictionaries of standard Italian' },
      { level: 3, code: '455', description: 'Grammar of standard Italian' },
      { level: 3, code: '457', description: 'Historical and geographic variations, modern nongeographic variations of Italian' },
      { level: 3, code: '458', description: 'Standard Italian usage (Prescriptive linguistics)' },
      { level: 2, code: '46', description: 'Spanish, Portuguese, Galician' },
      { level: 3, code: '460', description: 'Spanish, Portuguese, Galician' },
      { level: 3, code: '461', description: 'Writing systems, phonology, phonetics of standard Spanish' },
      { level: 3, code: '462', description: 'Etymology of standard Spanish' },
      { level: 3, code: '463', description: 'Dictionaries of standard Spanish' },
      { level: 3, code: '465', description: 'Grammar of standard Spanish' },
      { level: 3, code: '467', description: 'Historical and geographic variations, modern nongeographic variations of Spanish' },
      { level: 3, code: '468', description: 'Standard Spanish usage (Prescriptive linguistics)' },
      { level: 2, code: '47', description: 'Latin and Italic languages' },
      { level: 3, code: '470', description: 'Latin and related Italic languages' },
      { level: 3, code: '471', description: 'Writing systems, phonology, phonetics of classical Latin' },
      { level: 3, code: '472', description: 'Etymology of classical Latin' },
      { level: 3, code: '473', description: 'Dictionaries of classical Latin' },
      { level: 3, code: '475', description: 'Grammar of classical Latin' },
      { level: 3, code: '477', description: 'Old, postclassical, Vulgar Latin' },
      { level: 3, code: '478', description: 'Classical Latin usage (Prescriptive linguistics)' },
      { level: 2, code: '48', description: 'Classical and modern Greek languages' },
      { level: 3, code: '480', description: 'Classical Greek and related Hellenic languages' },
      { level: 3, code: '481', description: 'Writing systems, phonology, phonetics of classical Greek' },
      { level: 3, code: '482', description: 'Etymology of classical Greek' },
      { level: 3, code: '483', description: 'Dictionaries of classical Greek' },
      { level: 3, code: '485', description: 'Grammar of classical Greek' },
      { level: 3, code: '487', description: 'Preclassical and postclassical Greek' },
      { level: 3, code: '488', description: 'Classical Greek usage (Prescriptive linguistics)' },
      { level: 2, code: '49', description: 'Other languages' },
      { level: 3, code: '490', description: 'Other languages' },
      { level: 3, code: '491', description: 'East Indo-European and Celtic languages' },
      { level: 3, code: '492', description: 'Afro-Asiatic languages' },
      { level: 3, code: '493', description: 'Non-Semitic Afro-Asiatic languages' },
      { level: 3, code: '494', description: 'Altaic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of south Asia' },
      { level: 3, code: '495', description: 'Languages of East and Southeast Asia' },
      { level: 3, code: '496', description: 'African languages' },
      { level: 3, code: '497', description: 'North American native languages' },
      { level: 3, code: '498', description: 'South American native languages' },
      { level: 3, code: '499', description: 'Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages' },

      # 500s
      { level: 2, code: '50', description: 'Science' },
      { level: 3, code: '500', description: 'Natural sciences and mathematics' },
      { level: 3, code: '501', description: 'Philosophy and theory' },
      { level: 3, code: '502', description: 'Miscellany' },
      { level: 3, code: '503', description: 'Dictionaries, encyclopedias, concordances' },
      { level: 3, code: '505', description: 'Serial publications' },
      { level: 3, code: '506', description: 'Organizations and management' },
      { level: 3, code: '507', description: 'Education, research, related topics' },
      { level: 3, code: '508', description: 'Natural history' },
      { level: 3, code: '509', description: 'History, geographic treatment, biography' },
      { level: 2, code: '51', description: 'Mathematics' },
      { level: 3, code: '510', description: 'Mathematics' },
      { level: 3, code: '511', description: 'General principles of mathematics' },
      { level: 3, code: '512', description: 'Algebra' },
      { level: 3, code: '513', description: 'Arithmetic' },
      { level: 3, code: '514', description: 'Topology' },
      { level: 3, code: '515', description: 'Analysis' },
      { level: 3, code: '516', description: 'Geometry' },
      { level: 3, code: '518', description: 'Numerical analysis' },
      { level: 3, code: '519', description: 'Probabilities and applied mathematics' },
      { level: 2, code: '52', description: 'Astronomy' },
      { level: 3, code: '520', description: 'Astronomy and allied sciences' },
      { level: 3, code: '521', description: 'Celestial mechanics' },
      { level: 3, code: '522', description: 'Techniques, procedures, apparatus, equipment, materials' },
      { level: 3, code: '523', description: 'Specific celestial bodies and phenomena' },
      { level: 3, code: '525', description: 'Earth (Astronomical geography)' },
      { level: 3, code: '526', description: 'Mathematical geography' },
      { level: 3, code: '527', description: 'Celestial navigation' },
      { level: 3, code: '528', description: 'Ephemerides' },
      { level: 3, code: '529', description: 'Chronology' },
      { level: 2, code: '53', description: 'Physics' },
      { level: 3, code: '530', description: 'Physics' },
      { level: 3, code: '531', description: 'Classical mechanics' },
      { level: 3, code: '532', description: 'Fluid mechanics' },
      { level: 3, code: '533', description: 'Pneumatics (Gas mechanics)' },
      { level: 3, code: '534', description: 'Sound and related vibrations' },
      { level: 3, code: '535', description: 'Light and related radiation' },
      { level: 3, code: '536', description: 'Heat' },
      { level: 3, code: '537', description: 'Electricity and electronics' },
      { level: 3, code: '538', description: 'Magnetism' },
      { level: 3, code: '539', description: 'Modern physics' },
      { level: 2, code: '54', description: 'Chemistry' },
      { level: 3, code: '540', description: 'Chemistry and allied sciences' },
      { level: 3, code: '541', description: 'Physical chemistry' },
      { level: 3, code: '542', description: 'Techniques, procedures, apparatus, equipment, materials' },
      { level: 3, code: '543', description: 'Analytical chemistry' },
      { level: 3, code: '546', description: 'Inorganic chemistry' },
      { level: 3, code: '547', description: 'Organic chemistry' },
      { level: 3, code: '548', description: 'Crystallography' },
      { level: 3, code: '549', description: 'Mineralogy' },
      { level: 2, code: '55', description: 'Earth sciences and geology' },
      { level: 3, code: '550', description: 'Earth sciences' },
      { level: 3, code: '551', description: 'Geology, hydrology, meteorology' },
      { level: 3, code: '552', description: 'Petrology' },
      { level: 3, code: '553', description: 'Economic geology' },
      { level: 3, code: '554', description: 'Earth sciences of Europe' },
      { level: 3, code: '555', description: 'Earth sciences of Asia' },
      { level: 3, code: '556', description: 'Earth sciences of Africa' },
      { level: 3, code: '557', description: 'Earth sciences of North America' },
      { level: 3, code: '558', description: 'Earth sciences of South America' },
      { level: 3, code: '559', description: 'Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds' },
      { level: 2, code: '56', description: 'Fossils and prehistoric life' },
      { level: 3, code: '560', description: 'Paleontology' },
      { level: 3, code: '561', description: 'Paleobotany, fossil microorganisms' },
      { level: 3, code: '562', description: 'Fossil invertebrates' },
      { level: 3, code: '563', description: 'Miscellaneous fossil marine and seashore invertebrates' },
      { level: 3, code: '564', description: 'Fossil Mollusca and Molluscoidea' },
      { level: 3, code: '565', description: 'Fossil Arthropoda' },
      { level: 3, code: '566', description: 'Fossil Chordata' },
      { level: 3, code: '567', description: 'Fossil cold-blooded vertebrates' },
      { level: 3, code: '568', description: 'Fossil Aves (birds)' },
      { level: 3, code: '569', description: 'Fossil Mammalia' },
      { level: 2, code: '57', description: 'Biology' },
      { level: 3, code: '570', description: 'Biology' },
      { level: 3, code: '571', description: 'Physiology and related subjects' },
      { level: 3, code: '572', description: 'Biochemistry' },
      { level: 3, code: '573', description: 'Specific physiological systems in animals, regional histology and physiology in animals' },
      { level: 3, code: '575', description: 'Specific parts of and physiological systems in plants' },
      { level: 3, code: '576', description: 'Genetics and evolution' },
      { level: 3, code: '577', description: 'Ecology' },
      { level: 3, code: '578', description: 'Natural history of organisms and related subjects' },
      { level: 3, code: '579', description: 'Natural history of microorganisms, fungi, algae' },
      { level: 2, code: '58', description: 'Plants' },
      { level: 3, code: '580', description: 'Plants' },
      { level: 3, code: '581', description: 'Specific topics in natural history of plants' },
      { level: 3, code: '582', description: 'Plants noted for specific vegetative characteristics and flowers' },
      { level: 3, code: '583', description: 'Magnoliopsida (Dicotyledones)' },
      { level: 3, code: '584', description: 'Liliopsida (Monocotyledones)' },
      { level: 3, code: '585', description: 'Pinophyta (Gymnosperms)' },
      { level: 3, code: '586', description: 'Cryptogamia (Seedless plants)' },
      { level: 3, code: '587', description: 'Pteridophyta' },
      { level: 3, code: '588', description: 'Bryophyta' },
      { level: 2, code: '59', description: 'Animals (Zoology)' },
      { level: 3, code: '590', description: 'Animals' },
      { level: 3, code: '591', description: 'Specific topics in natural history of animals' },
      { level: 3, code: '592', description: 'Invertebrates' },
      { level: 3, code: '593', description: 'Miscellaneous marine and seashore invertebrates' },
      { level: 3, code: '594', description: 'Mollusca and Molluscoidea' },
      { level: 3, code: '595', description: 'Arthropoda' },
      { level: 3, code: '596', description: 'Chordata' },
      { level: 3, code: '597', description: 'Cold-blooded vertebrates' },
      { level: 3, code: '598', description: 'Aves (Birds)' },
      { level: 3, code: '599', description: 'Mammalia (Mammals)' },

      { level: 2, code: '60', description: 'Technology' },
      { level: 3, code: '600', description: 'Technology (Applied sciences)' },
      { level: 3, code: '601', description: 'Philosophy and theory' },
      { level: 3, code: '602', description: 'Miscellany' },
      { level: 3, code: '603', description: 'Dictionaries, encyclopedias, concordances' },
      { level: 3, code: '604', description: 'Technical drawing, hazardous materials technology; groups of people' },
      { level: 3, code: '605', description: 'Serial publications' },
      { level: 3, code: '606', description: 'Organizations' },
      { level: 3, code: '607', description: 'Education, research, related topics' },
      { level: 3, code: '608', description: 'Patents' },
      { level: 3, code: '609', description: 'History, geographic treatment, biography' },
      { level: 2, code: '61', description: 'Medicine and health' },
      { level: 3, code: '610', description: 'Medicine and health' },
      { level: 3, code: '611', description: 'Human anatomy, cytology, histology' },
      { level: 3, code: '612', description: 'Human physiology' },
      { level: 3, code: '613', description: 'Personal health and safety' },
      { level: 3, code: '614', description: 'Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine' },
      { level: 3, code: '615', description: 'Pharmacology and therapeutics' },
      { level: 3, code: '616', description: 'Diseases' },
      { level: 3, code: '617', description: 'Surgery, regional medicine, dentistry, ophthalmology, otology, audiology' },
      { level: 3, code: '618', description: 'Gynecology, obstetrics, pediatrics, geriatrics' },
      { level: 2, code: '62', description: 'Engineering' },
      { level: 3, code: '620', description: 'Engineering and applied operations' },
      { level: 3, code: '621', description: 'Applied physics' },
      { level: 3, code: '622', description: 'Mining and related operations' },
      { level: 3, code: '623', description: 'Military and nautical engineering' },
      { level: 3, code: '624', description: 'Civil engineering' },
      { level: 3, code: '627', description: 'Hydraulic engineering' },
      { level: 3, code: '628', description: 'Sanitary engineering' },
      { level: 3, code: '629', description: 'Other branches of engineering' },
      { level: 2, code: '63', description: 'Agriculture' },
      { level: 3, code: '630', description: 'Agriculture and related technologies' },
      { level: 3, code: '631', description: 'Specific techniques; apparatus, equipment, materials' },
      { level: 3, code: '632', description: 'Plant injuries, diseases, pests' },
      { level: 3, code: '633', description: 'Field and plantation crops' },
      { level: 3, code: '634', description: 'Orchards, fruits, forestry' },
      { level: 3, code: '635', description: 'Garden crops (Horticulture)' },
      { level: 3, code: '636', description: 'Animal husbandry' },
      { level: 3, code: '637', description: 'Processing dairy and related products' },
      { level: 3, code: '638', description: 'Insect culture' },
      { level: 3, code: '639', description: 'Hunting, fishing, conservation, related technologies' },
      { level: 2, code: '64', description: 'Home and family management' },
      { level: 3, code: '640', description: 'Home and family management' },
      { level: 3, code: '641', description: 'Food and drink' },
      { level: 3, code: '642', description: 'Meals and table service' },
      { level: 3, code: '643', description: 'Housing and household equipment' },
      { level: 3, code: '644', description: 'Household utilities' },
      { level: 3, code: '645', description: 'Household furnishings' },
      { level: 3, code: '646', description: 'Sewing, clothing, management of personal and family life' },
      { level: 3, code: '647', description: 'Management of public households (Institutional housekeeping)' },
      { level: 3, code: '648', description: 'Housekeeping' },
      { level: 3, code: '649', description: 'Child rearing; home care of people with disabilities and illnesses' },
      { level: 2, code: '65', description: 'Management and public relations' },
      { level: 3, code: '650', description: 'Management and auxiliary services' },
      { level: 3, code: '651', description: 'Office services' },
      { level: 3, code: '652', description: 'Processes of written communication' },
      { level: 3, code: '653', description: 'Shorthand' },
      { level: 3, code: '657', description: 'Accounting' },
      { level: 3, code: '658', description: 'General management' },
      { level: 3, code: '659', description: 'Advertising and public relations' },
      { level: 2, code: '66', description: 'Chemical engineering' },
      { level: 3, code: '660', description: 'Chemical engineering and related technologies' },
      { level: 3, code: '661', description: 'Technology of industrial chemicals' },
      { level: 3, code: '662', description: 'Technology of explosives, fuels, related products' },
      { level: 3, code: '663', description: 'Beverage technology' },
      { level: 3, code: '664', description: 'Food technology' },
      { level: 3, code: '665', description: 'Technology of industrial oils, fats, waxes, gases' },
      { level: 3, code: '666', description: 'Ceramic and allied technologies' },
      { level: 3, code: '667', description: 'Cleaning, color, coating, related technologies' },
      { level: 3, code: '668', description: 'Technology of other organic products' },
      { level: 3, code: '669', description: 'Metallurgy' },
      { level: 2, code: '67', description: 'Manufacturing' },
      { level: 3, code: '670', description: 'Manufacturing' },
      { level: 3, code: '671', description: 'Metalworking processes and primary metal products' },
      { level: 3, code: '672', description: 'Iron, steel, other iron alloys' },
      { level: 3, code: '673', description: 'Nonferrous metals' },
      { level: 3, code: '674', description: 'Lumber processing, wood products, cork' },
      { level: 3, code: '675', description: 'Leather and fur processing' },
      { level: 3, code: '676', description: 'Pulp and paper technology' },
      { level: 3, code: '677', description: 'Textiles' },
      { level: 3, code: '678', description: 'Elastomers and elastomer products' },
      { level: 3, code: '679', description: 'Other products of specific kinds of materials' },
      { level: 2, code: '68', description: 'Manufacture for specific uses' },
      { level: 3, code: '680', description: 'Manufacture of products for specific uses' },
      { level: 3, code: '681', description: 'Precision instruments and other devices' },
      { level: 3, code: '682', description: 'Small forge work (Blacksmithing)' },
      { level: 3, code: '683', description: 'Hardware and household appliances' },
      { level: 3, code: '684', description: 'Furnishings and home workshops' },
      { level: 3, code: '685', description: 'Leather and fur goods, and related products' },
      { level: 3, code: '686', description: 'Printing and related activities' },
      { level: 3, code: '687', description: 'Clothing and accessories' },
      { level: 3, code: '688', description: 'Other final products, and packaging technology' },
      { level: 2, code: '69', description: 'Construction of buildings' },
      { level: 3, code: '690', description: 'Construction of buildings' },
      { level: 3, code: '691', description: 'Building materials' },
      { level: 3, code: '692', description: 'Auxiliary construction practices' },
      { level: 3, code: '693', description: 'Construction in specific types of materials and for specific purposes'},
      { level: 3, code: '694', description: 'Wood construction'},
      { level: 3, code: '695', description: 'Roof covering'},
      { level: 3, code: '696', description: 'Utilities'},
      { level: 3, code: '697', description: 'Heating, ventilating, air-conditioning engineering'},
      { level: 3, code: '698', description: 'Detail finishing'},

      { level: 2, code: '70', description: 'Arts' },
      { level: 3, code: '700', description: 'The Arts' },
      { level: 3, code: '701', description: 'Philosophy and theory of fine and decorative arts' },
      { level: 3, code: '702', description: 'Miscellany of fine and decorative arts' },
      { level: 3, code: '703', description: 'Dictionaries, encyclopedias, concordances of fine and decorative arts' },
      { level: 3, code: '704', description: 'Special topics in fine and decorative arts' },
      { level: 3, code: '705', description: 'Serial publications of fine and decorative arts' },
      { level: 3, code: '706', description: 'Organizations and management of fine and decorative arts' },
      { level: 3, code: '707', description: 'Education, research, related topics of fine and decorative arts' },
      { level: 3, code: '708', description: 'Galleries, museums, private collections of fine and decorative arts' },
      { level: 3, code: '709', description: 'History, geographic treatment, biography' },
      { level: 2, code: '71', description: 'Area planning and landscape architecture' },
      { level: 3, code: '710', description: 'Area planning (Civic art)' },
      { level: 3, code: '711', description: 'Landscape architecture (Landscape design)' },
      { level: 3, code: '712', description: 'Landscape architecture of trafficways' },
      { level: 3, code: '713', description: 'Landscape architecture of water features' },
      { level: 3, code: '714', description: 'Woody plants in landscape architecture' },
      { level: 3, code: '715', description: 'Herbaceous plants in landscape architecture' },
      { level: 3, code: '716', description: 'Structures in landscape architecture' },
      { level: 3, code: '717', description: 'Landscape design of cemeteries' },
      { level: 3, code: '718', description: 'Natural landscapes' },
      { level: 2, code: '72', description: 'Architecture' },
      { level: 3, code: '720', description: 'Architecture' },
      { level: 3, code: '721', description: 'Architectural materials and structural elements' },
      { level: 3, code: '722', description: 'Architecture from earliest times to c.300' },
      { level: 3, code: '723', description: 'Architecture from c.300 to 1399' },
      { level: 3, code: '724', description: 'Architecture from 1400' },
      { level: 3, code: '725', description: 'Public structures' },
      { level: 3, code: '726', description: 'Buildings for religious and related purposes' },
      { level: 3, code: '727', description: 'Buildings for educational and research purposes' },
      { level: 3, code: '728', description: 'Residential and related buildings' },
      { level: 3, code: '729', description: 'Design and decoration of structures and accessories' },
      { level: 2, code: '73', description: 'Sculpture, ceramics and metalwork' },
      { level: 3, code: '730', description: 'Sculpture and related arts' },
      { level: 3, code: '731', description: 'Processes, forms, subjects of sculpture' },
      { level: 3, code: '732', description: 'Sculpture from earliest times to c.500' },
      { level: 3, code: '733', description: 'Greek, Etruscan, Roman sculpture' },
      { level: 3, code: '734', description: 'Sculpture from ca 500 to 1399' },
      { level: 3, code: '735', description: 'Sculpture from 1400' },
      { level: 3, code: '736', description: 'Carving and carvings' },
      { level: 3, code: '737', description: 'Numismatics and sigillography' },
      { level: 3, code: '738', description: 'Ceramic arts' },
      { level: 3, code: '739', description: 'Art metalwork' },
      { level: 2, code: '74', description: 'Graphic arts and decorative arts' },
      { level: 3, code: '740', description: 'Graphic arts' },
      { level: 3, code: '741', description: 'Drawing and drawings' },
      { level: 3, code: '742', description: 'Perspective in drawing' },
      { level: 3, code: '743', description: 'Drawing and drawings by subject' },
      { level: 3, code: '744', description: 'Communication design and visual design' },
      { level: 3, code: '745', description: 'Decorative arts' },
      { level: 3, code: '746', description: 'Textile arts' },
      { level: 3, code: '747', description: 'Interior decoration' },
      { level: 3, code: '748', description: 'Glass' },
      { level: 3, code: '749', description: 'Furniture and accessories' },
      { level: 2, code: '75', description: 'Painting' },
      { level: 3, code: '750', description: 'Painting and paintings' },
      { level: 3, code: '751', description: 'Techniques, procedures, apparatus, equipment, materials, forms' },
      { level: 3, code: '752', description: 'Color' },
      { level: 3, code: '753', description: 'Symbolism, allegory, mythology, legend' },
      { level: 3, code: '754', description: 'Genre paintings' },
      { level: 3, code: '755', description: 'Religion' },
      { level: 3, code: '757', description: 'Human figures' },
      { level: 3, code: '758', description: 'Nature, architectural subjects and cityscapes, other specific subjects' },
      { level: 3, code: '759', description: 'History, geographic treatment, biography' },
      { level: 2, code: '76', description: 'Printmaking and prints' },
      { level: 3, code: '760', description: 'Printmaking and prints' },
      { level: 3, code: '761', description: 'Relief processes (Block printing)' },
      { level: 3, code: '763', description: 'Lithographic processes (Planographic processes)' },
      { level: 3, code: '764', description: 'Chromolithography and serigraphy' },
      { level: 3, code: '765', description: 'Metal engraving' },
      { level: 3, code: '766', description: 'Mezzotinting, aquatinting, and related processes' },
      { level: 3, code: '767', description: 'Etching and drypoint' },
      { level: 3, code: '769', description: 'Prints' },
      { level: 2, code: '77', description: 'Photography, computer art, film, video' },
      { level: 3, code: '770', description: 'Photography, computer art, cinematography, videography' },
      { level: 3, code: '771', description: 'Techniques, procedures, apparatus, equipment, materials' },
      { level: 3, code: '772', description: 'Metallic salt processes' },
      { level: 3, code: '773', description: 'Pigment processes of printing' },
      { level: 3, code: '776', description: 'Computer art (Digital art)' },
      { level: 3, code: '777', description: 'Cinematography and Videography' },
      { level: 3, code: '779', description: 'Photographic images' },
      { level: 2, code: '78', description: 'Music' },
      { level: 3, code: '780', description: 'Music' },
      { level: 3, code: '781', description: 'General principles and musical forms' },
      { level: 3, code: '782', description: 'Vocal music' },
      { level: 3, code: '783', description: 'Music for single voices' },
      { level: 3, code: '784', description: 'Instruments and Instrumental ensembles and their music' },
      { level: 3, code: '785', description: 'Ensembles with only one instrument per part' },
      { level: 3, code: '786', description: 'Keyboard, mechanical, electrophonic, percussion instruments' },
      { level: 3, code: '787', description: 'Stringed instruments (Chordophones)' },
      { level: 3, code: '788', description: 'Wind instruments (Aerophones)' },
      { level: 2, code: '79', description: 'Sports, games and entertainment' },
      { level: 3, code: '790', description: 'Recreational and performing arts' },
      { level: 3, code: '791', description: 'Public performances' },
      { level: 3, code: '792', description: 'Stage presentations' },
      { level: 3, code: '793', description: 'Indoor games and amusements' },
      { level: 3, code: '794', description: 'Indoor games of skill' },
      { level: 3, code: '795', description: 'Games of chance' },
      { level: 3, code: '796', description: 'Athletic and outdoor sports and games' },
      { level: 3, code: '797', description: 'Aquatic and air sports' },
      { level: 3, code: '798', description: 'Equestrian sports and animal racing' },
      { level: 3, code: '799', description: 'Fishing, hunting, shooting' },

      { level: 2, code: '80', description: 'Literature' },
      { level: 3, code: '800', description: 'Literature, rhetoric and criticism' },
      { level: 3, code: '801', description: 'Philosophy and theory' },
      { level: 3, code: '802', description: 'Miscellany' },
      { level: 3, code: '803', description: 'Dictionaries, encyclopedias, concordances' },
      { level: 3, code: '805', description: 'Serial publications' },
      { level: 3, code: '806', description: 'Organizations and management' },
      { level: 3, code: '807', description: 'Education, research, related topics' },
      { level: 3, code: '808', description: 'Rhetoric and collections of literary texts from more than two literatures' },
      { level: 3, code: '809', description: 'History, description, critical appraisal of more than two literatures' },
      { level: 2, code: '81', description: 'American literature in English' },
      { level: 3, code: '810', description: 'American literature in English' },
      { level: 3, code: '811', description: 'American poetry in English' },
      { level: 3, code: '812', description: 'American drama in English' },
      { level: 3, code: '813', description: 'American fiction in English' },
      { level: 3, code: '814', description: 'American essays in English' },
      { level: 3, code: '815', description: 'American speeches in English' },
      { level: 3, code: '816', description: 'American letters in English' },
      { level: 3, code: '817', description: 'American humor and satire in English' },
      { level: 3, code: '818', description: 'American miscellaneous writings in English' },
      { level: 2, code: '82', description: 'English and Old English literatures' },
      { level: 3, code: '820', description: 'English and Old English (Anglo-Saxon) literatures' },
      { level: 3, code: '821', description: 'English poetry' },
      { level: 3, code: '822', description: 'English drama' },
      { level: 3, code: '823', description: 'English fiction' },
      { level: 3, code: '824', description: 'English essays' },
      { level: 3, code: '825', description: 'English speeches' },
      { level: 3, code: '826', description: 'English letters' },
      { level: 3, code: '827', description: 'English humor and satire' },
      { level: 3, code: '828', description: 'English miscellaneous writings' },
      { level: 3, code: '829', description: 'Old English (Anglo-Saxon) literature' },
      { level: 2, code: '83', description: 'German and related literatures' },
      { level: 3, code: '830', description: 'German literature and literatures of related languages' },
      { level: 3, code: '831', description: 'German poetry' },
      { level: 3, code: '832', description: 'German drama' },
      { level: 3, code: '833', description: 'German fiction' },
      { level: 3, code: '834', description: 'German essays' },
      { level: 3, code: '835', description: 'German speeches' },
      { level: 3, code: '836', description: 'German letters' },
      { level: 3, code: '837', description: 'German humor and satire' },
      { level: 3, code: '838', description: 'German miscellaneous writings' },
      { level: 3, code: '839', description: 'Other Germanic literatures' },
      { level: 2, code: '84', description: 'French and related literatures' },
      { level: 3, code: '840', description: 'French literature and literatures of related Romance languages' },
      { level: 3, code: '841', description: 'French poetry' },
      { level: 3, code: '842', description: 'French drama' },
      { level: 3, code: '843', description: 'French fiction' },
      { level: 3, code: '844', description: 'French essays' },
      { level: 3, code: '845', description: 'French speeches' },
      { level: 3, code: '846', description: 'French letters' },
      { level: 3, code: '847', description: 'French humor and satire' },
      { level: 3, code: '848', description: 'French miscellaneous writings' },
      { level: 3, code: '849', description: 'Occitan, Catalan, Franco-Provençal literatures' },
      { level: 2, code: '85', description: 'Italian, Romanian and related literatures' },
      { level: 3, code: '850', description: 'Literatures of Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican languages' },
      { level: 3, code: '851', description: 'Italian poetry' },
      { level: 3, code: '852', description: 'Italian drama' },
      { level: 3, code: '853', description: 'Italian fiction' },
      { level: 3, code: '854', description: 'Italian essays' },
      { level: 3, code: '855', description: 'Italian speeches' },
      { level: 3, code: '856', description: 'Italian letters' },
      { level: 3, code: '857', description: 'Italian humor and satire' },
      { level: 3, code: '858', description: 'Italian miscellaneous writings' },
      { level: 3, code: '859', description: 'Literatures of Romanian, Rhaetian, Sardinian, Corsican languages' },
      { level: 2, code: '86', description: 'Spanish, Portuguese, Galician literatures' },
      { level: 3, code: '860', description: 'Literatures of Spanish, Portuguese, Galician languages' },
      { level: 3, code: '861', description: 'Spanish poetry' },
      { level: 3, code: '862', description: 'Spanish drama' },
      { level: 3, code: '863', description: 'Spanish fiction' },
      { level: 3, code: '864', description: 'Spanish essays' },
      { level: 3, code: '865', description: 'Spanish speeches' },
      { level: 3, code: '866', description: 'Spanish letters' },
      { level: 3, code: '867', description: 'Spanish humor and satire' },
      { level: 3, code: '868', description: 'Spanish miscellaneous writings' },
      { level: 3, code: '869', description: 'Literatures of Portuguese and Galician languages' },
      { level: 2, code: '87', description: 'Latin and Italic literatures' },
      { level: 3, code: '870', description: 'Latin literature and literatures of related Italic languages' },
      { level: 3, code: '871', description: 'Latin poetry' },
      { level: 3, code: '872', description: 'Latin dramatic poetry and drama' },
      { level: 3, code: '873', description: 'Latin epic poetry and fiction' },
      { level: 3, code: '874', description: 'Latin lyric poetry' },
      { level: 3, code: '875', description: 'Latin speeches' },
      { level: 3, code: '876', description: 'Latin letters' },
      { level: 3, code: '877', description: 'Latin humor and satire' },
      { level: 3, code: '878', description: 'Latin miscellaneous writings' },
      { level: 3, code: '879', description: 'Literatures of other Italic languages' },
      { level: 2, code: '88', description: 'Classical and modern Greek literatures' },
      { level: 3, code: '880', description: 'Classical Greek literature and literatures of related Hellenic languages' },
      { level: 3, code: '881', description: 'Classical Greek poetry' },
      { level: 3, code: '882', description: 'Classical Greek drama' },
      { level: 3, code: '883', description: 'Classical Greek epic poetry and fiction' },
      { level: 3, code: '884', description: 'Classical Greek lyric poetry' },
      { level: 3, code: '885', description: 'Classical Greek speeches' },
      { level: 3, code: '886', description: 'Classical Greek letters' },
      { level: 3, code: '887', description: 'Classical Greek humor and satire' },
      { level: 3, code: '888', description: 'Classical Greek miscellaneous writings'},
      { level: 3, code: '889', description: 'Modern Greek literature'},

      { level: 2, code: '89', description: 'Other literatures' },
      { level: 3, code: '890', description: 'Literatures of other specific languages and language families' },
      { level: 3, code: '891', description: 'East Indo-European and Celtic literatures' },
      { level: 3, code: '892', description: 'Afro-Asiatic literatures' },
      { level: 3, code: '893', description: 'Non-Semitic Afro-Asiatic literatures' },
      { level: 3, code: '894', description: 'Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of South Asia' },
      { level: 3, code: '895', description: 'Literatures of East and Southeast Asia' },
      { level: 3, code: '896', description: 'African literatures' },
      { level: 3, code: '897', description: 'Literatures of North American native languages' },
      { level: 3, code: '898', description: 'Literatures of South American native languages'},
      { level: 3, code: '899', description: 'Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages'},


      { level: 2, code: '90', description: 'History and geography' },
      { level: 3, code: '900', description: 'History, geography, and auxiliary disciplines' },
      { level: 3, code: '901', description: 'Philosophy and theory of history' },
      { level: 3, code: '902', description: 'Miscellany of history' },
      { level: 3, code: '903', description: 'Dictionaries, encyclopedias, concordances of history' },
      { level: 3, code: '904', description: 'Collected accounts of events' },
      { level: 3, code: '905', description: 'Serial publications of history' },
      { level: 3, code: '906', description: 'Organizations and management of history' },
      { level: 3, code: '907', description: 'Education, research, related topics of history' },
      { level: 3, code: '908', description: 'History with respect to groups of people' },
      { level: 3, code: '909', description: 'World history' },
      { level: 2, code: '91', description: 'Geography and travel' },
      { level: 3, code: '910', description: 'Geography and travel' },
      { level: 3, code: '911', description: 'Historical geography' },
      { level: 3, code: '912', description: 'Graphic representations of surface of Earth and of extraterrestrial worlds' },
      { level: 3, code: '913', description: 'Geography of and travel in the ancient world' },
      { level: 3, code: '914', description: 'Geography of and travel in Europe' },
      { level: 3, code: '915', description: 'Geography of and travel in Asia' },
      { level: 3, code: '916', description: 'Geography of and travel in Africa' },
      { level: 3, code: '917', description: 'Geography of and travel in North America' },
      { level: 3, code: '918', description: 'Geography of and travel in South America' },
      { level: 3, code: '919', description: 'Geography of and travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, and on extraterrestrial worlds' },
      { level: 2, code: '92', description: 'Biography and genealogy' },
      { level: 3, code: '920', description: 'Biography, genealogy, insignia' },
      { level: 3, code: '929', description: 'Genealogy, names, insignia' },
      { level: 2, code: '93', description: 'History of ancient world (to c.499)' },
      { level: 3, code: '930', description: 'History of ancient world (to c.499)' },
      { level: 3, code: '931', description: 'China to 420' },
      { level: 3, code: '932', description: 'Egypt to 640' },
      { level: 3, code: '933', description: 'Palestine to 70' },
      { level: 3, code: '934', description: 'South Asia to 647' },
      { level: 3, code: '935', description: 'Mesopotamia and Iranian Plateau to 637' },
      { level: 3, code: '936', description: 'Europe north and west of Italian Peninsula to c.499' },
      { level: 3, code: '937', description: 'Italy and adjacent territories to 476' },
      { level: 3, code: '938', description: 'Greece to 323' },
      { level: 3, code: '939', description: 'Other parts of ancient world' },
      { level: 2, code: '94', description: 'History of Europe' },
      { level: 3, code: '940', description: 'History of Europe' },
      { level: 3, code: '941', description: 'British Isles' },
      { level: 3, code: '942', description: 'England and Wales' },
      { level: 3, code: '943', description: 'Germany and neighboring central European countries' },
      { level: 3, code: '944', description: 'France and Monaco' },
      { level: 3, code: '945', description: 'Italy, San Marino, Vatican City, Malta' },
      { level: 3, code: '946', description: 'Spain, Andorra, Gibraltar, Portugal' },
      { level: 3, code: '947', description: 'Russia and neighboring east European countries' },
      { level: 3, code: '948', description: 'Scandinavia' },
      { level: 3, code: '949', description: 'Other parts of Europe' },
      { level: 2, code: '95', description: 'History of Asia' },
      { level: 3, code: '950', description: 'History of Asia' },
      { level: 3, code: '951', description: 'China and adjacent areas' },
      { level: 3, code: '952', description: 'Japan' },
      { level: 3, code: '953', description: 'Arabian Peninsula and adjacent areas' },
      { level: 3, code: '954', description: 'India and neighboring south Asian countries' },
      { level: 3, code: '955', description: 'Iran' },
      { level: 3, code: '956', description: 'Middle East (Near East)' },
      { level: 3, code: '957', description: 'Siberia (Asiatic Russia)' },
      { level: 3, code: '958', description: 'Central Asia' },
      { level: 3, code: '959', description: 'Southeast Asia' },
      { level: 2, code: '96', description: 'History of Africa' },
      { level: 3, code: '960', description: 'History of Africa' },
      { level: 3, code: '961', description: 'Tunisia and Libya' },
      { level: 3, code: '962', description: 'Egypt, Sudan, South Sudan' },
      { level: 3, code: '963', description: 'Ethiopia and Eritrea' },
      { level: 3, code: '964', description: 'Morocco, Ceuta, Melilla, Western Sahara, Canary Islands' },
      { level: 3, code: '965', description: 'Algeria' },
      { level: 3, code: '966', description: 'West Africa and offshore islands' },
      { level: 3, code: '967', description: 'Central Africa and offshore islands' },
      { level: 3, code: '968', description: 'South Africa & southern Africa' },
      { level: 3, code: '969', description: 'South Indian Ocean islands' },
      { level: 2, code: '97', description: 'History of North America' },
      { level: 3, code: '970', description: 'History of North America' },
      { level: 3, code: '971', description: 'Canada' },
      { level: 3, code: '972', description: 'Mexico, Central America, West Indies, Bermuda' },
      { level: 3, code: '973', description: 'United States' },
      { level: 3, code: '974', description: 'Northeastern United States (New England and Middle Atlantic states)' },
      { level: 3, code: '975', description: 'Southeastern United States (South Atlantic states)' },
      { level: 3, code: '976', description: 'South central United States' },
      { level: 3, code: '977', description: 'North central United States' },
      { level: 3, code: '978', description: 'Western United States' },
      { level: 3, code: '979', description: 'Great Basin and Pacific Slope region of United States' },
      { level: 2, code: '98', description: 'History of South America' },
      { level: 3, code: '980', description: 'History of South America' },
      { level: 3, code: '981', description: 'Brazil' },
      { level: 3, code: '982', description: 'Argentina' },
      { level: 3, code: '983', description: 'Chile' },
      { level: 3, code: '984', description: 'Bolivia' },
      { level: 3, code: '985', description: 'Peru' },
      { level: 3, code: '986', description: 'Colombia and Ecuador' },
      { level: 3, code: '987', description: 'Venezuela' },
      { level: 3, code: '988', description: 'Guiana' },
      { level: 3, code: '989', description: 'Paraguay and Uruguay' },
      { level: 2, code: '99', description: 'History of other areas' },
      { level: 3, code: '990', description: 'History of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds'},
      { level: 3, code: '993', description: 'New Zealand' },
      { level: 3, code: '994', description: 'Australia' },
      { level: 3, code: '995', description: 'New Guinea and neighboring countries of Melanesia' },
      { level: 3, code: '996', description: 'Polynesia and other Pacific Ocean islands' },
      { level: 3, code: '997', description: 'Atlantic Ocean islands' },
      { level: 3, code: '998', description: 'Arctic islands and Antarctica' },
      { level: 3, code: '999', description: 'Extraterrestrial worlds' },

    ]

    dewey_codes.each do |code|
      DeweyCode.create(code)
    end
  end
end
